### ISSUE TITLE
Reboot issues using "restart: on-failure"

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode-project#252]
@luca in the main `docker-compose` file the `restart: unless-stopped` have been changed to `restart: on-failure`.
This change seems not be relaunching some of the service after a reboot.
Why this change has been done? Can it be reverted?

**Comment by randomorder** [comment]
do you know @lpasquali ?

**Comment by simboss** [comment]
I do!

**Comment by frafra** [comment]
It should be restarted with a delay, in my opinion, and a maximum number of tentatives, to avoid having geonode flooding the server by spawning thousands of containers in a short amount of time.

**Comment by lpasquali** [comment]
@randomorder @etj I think (git blames actually) https://github.com/GeoNode/geonode-project/commit/31c1e6a3b30f3350faaa664d3d8d77fc1bac696c

**Comment by lpasquali** [comment]
@etj @randomorder 
fixed for master and 3.3.x 

https://github.com/GeoNode/geonode-project/pull/253
https://github.com/GeoNode/geonode-project/pull/254

**Comment by afabiani** [comment]
@etj @randomorder please see the comments here

https://github.com/GeoNode/geonode-project/pull/253#issuecomment-945537673

**Comment by afabiani** [comment]
Please update accordingly to the comment below:
"It should be restarted with a delay, in my opinion, and a maximum number of tentatives, to avoid having geonode flooding the server by spawning thousands of containers in a short amount of time."

**Comment by frafra** [comment]
`restart` is the main directive that can be used to specify when a container should be restarted or not. It is also used to start the container automatically when docker starts (when the system boots, usually), by using `restart: always`. That could be problematic if there is an error in the configuration, or if one container is unable to start, and the containers reboots forever.

It is possible to specify a more sophisticated policy, using `restart_policy`: https://docs.docker.com/compose/compose-file/compose-file-v3/#restart_policy.

Here is a snippet I use to apply the same `restart_policy` to all the containers (it uses yaml anchors):

```yaml
x-common-deployment:
  &default-common-deployment
  deploy:
    replicas: 1
    restart_policy:
      condition: any
      delay: 0s
      max_attempts: 10
      window: 60s

services:
  geonode:
    << : *default-common-deployment
    # ...
  geoserver:
    << : *default-common-deployment
    # ...
```

That should be good enough for both development and production: it will always restart the services, but with a long delay, so that developers can understand something bad happened, and sysadmins can avoid flooding.

A simpler `restart: always` option could be added along `restart_policy`, to achieve the highest compatibility, as  `restart` is used if the Docker node does not use Docker Swarm, while `restart_policy` is used if Docker Swarm is enabled. We could suggest to sysadmin to enable docker swarm when possible, executing `docker swarm init`: https://docs.docker.com/engine/swarm/swarm-mode/.

A possible alternative would be to avoid restarting containers and run `docker-compose up` at boot. I would advise against that, as systemd has no knowledge about what is happening within the stacks, so different systemd services should be created, which is what can be accomplished more easily by enabling docker swarm.
- https://community.hetzner.com/tutorials/docker-compose-as-systemd-service#step-2---create-the-systemd-service-template
- https://stackoverflow.com/a/48066454/1312346

**Comment by lpasquali** [comment]
Hello @randomorder @afabiani @frafra 
I implemented a docker-compose v 3.9 composition with `restart_policy`, this as underlined by @frafra needs docker swarm to be initiated even if for one node, this is actually not a big deal, but in other to let test others I added a Vagrantfile and an antani-vagrant.sh script which create a vagrant virtualbox instance with Ubuntu focal and builds a fresh generated project on a linux box with docker and docker-compose and swarm initialization.
`restart_policy` with vagrant can be tested like (edit Vagrantfile $geonode_source_path to point to a geonode-project repository at desired branch):
```bash
vagrant up
vagrant ssh
docker ps
sudo reboot
vagrant ssh
docker ps
```

**Comment by lpasquali** [comment]
@randomorder @afabiani testing extensively this solution with "mixed" swarm configuration, I see that repartition of services on reboot is not working

**Comment by randomorder** [comment]
please propose a solution @lpasquali

**Comment by lpasquali** [comment]
@randomorder for the sake of @etj original request I would revert everything to just what was asked: that where a restart parameter changed we re-add back the old woring restart: unless-stopped

**Comment by giohappy** [comment]
@lpasquali I'm fine with re-adding the `unless-stopped` policy, but it's not clear to me if having it along with the `restart-policy` (for Swarm) causes probelms

**Comment by randomorder** [comment]
agreed with @giohappy 
please revert @lpasquali 
if we add support for swarm in the future we will take care of testing the restart policies,,

**Comment by lpasquali** [comment]
> @lpasquali I'm fine with re-adding the `unless-stopped` policy, but it's not clear to me if having it along with the `restart-policy` (for Swarm) causes probelms

I have never seen it on usual docker-compose, I would suggest to "fork" docker-compose.yml" to "geonode-stack.yml" so that we can have both of them, from my PR I wuold anyway suggest to push the vagrant scripting I did, which gives an handy pre-generated on demand local system for geonode-project deployment in vscode. @giohappy

**Comment by giohappy** [comment]
As said @lpasquali just revert to `unless-stopped`.
If you have a vagrant script send it in a separate PR.

**Comment by frafra** [comment]
> @lpasquali I'm fine with re-adding the `unless-stopped` policy, but it's not clear to me if having it along with the `restart-policy` (for Swarm) causes probelms

We can have them both, unless they have different policies. `restart: always` and `condition: any` for the docker swarm option. If a user wants better handling, it would just enable docker swarm. That is the most compatible and easy to use setup in my opinion. No need to have multiple files to maintain and such.

**Comment by giohappy** [comment]
@lpasquali could you make a final test with the hints from @frafra? From what he says he's deploying GeoNode with Swarm and this mix of policies is not harming...

**Comment by lpasquali** [comment]
> @lpasquali could you make a final test with the hints from @frafra? From what he says he's deploying GeoNode with Swarm and this mix of policies is not harming...
yes I can @giohappy but I would still avoid to use same file... so if two compositions are too hard to maintain, we can always put the swarm stuff as an override and easily tell tah for swar one need to run something like:
```
docker stack deploy --compose-file docker-compose.yml --compose-file docker-compose.swarm-verride.yml
```
Harming or not I would like to be still be able to push yaml code to be parsed by docker-compose.yml that actually is supported and similar to its predecessors on old installs, and only swarm code where there is a swarm cluster enabled.

**Comment by giohappy** [comment]
I think this is a good compromise, and keeps things separated and clear @lpasquali

**Comment by afabiani** [comment]
so far this is my proposal

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index eaa7d5e..ac4789f 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -5,7 +5,7 @@ services:
 x-common-django:
   &default-common-django
   image: ${COMPOSE_PROJECT_NAME}_django:latest
-  restart: on-failure
+  restart: unless-stopped
   env_file:
     - .env
   volumes:
@@ -67,7 +67,7 @@ services:
       - nginx-confd:/etc/nginx
       - nginx-certificates:/geonode-certificates
       - statics:/mnt/volumes/statics
-    restart: on-failure
+    restart: unless-stopped
 
   # Gets and installs letsencrypt certificates
   letsencrypt:
@@ -81,7 +81,7 @@ services:
       - LETSENCRYPT_MODE=${LETSENCRYPT_MODE}
     volumes:
       - nginx-certificates:/geonode-certificates
-    restart: on-failure
+    restart: unless-stopped
 
   # Geoserver backend
   geoserver:
@@ -102,7 +102,7 @@ services:
       - backup-restore:/backup_restore
       - data:/data
       - tmp:/tmp
-    restart: on-failure
+    restart: unless-stopped
 
   data-dir-conf:
     image: geonode/geoserver_data:2.19.x
@@ -110,8 +110,6 @@ services:
     command: /bin/true
     volumes:
       - geoserver-data-dir:/geoserver_data/data
-    restart: on-failure
-
 
   # Vanilla RabbitMQ service. This is needed by celery
   rabbitmq:
@@ -119,7 +117,7 @@ services:
     container_name: rabbitmq4${COMPOSE_PROJECT_NAME}
     volumes:
       - rabbitmq:/var/lib/rabbitmq
-    restart: on-failure
+    restart: unless-stopped
 
   jenkins:
     image: jenkins/jenkins:lts
```

**Comment by lpasquali** [comment]
hello @giohappy @afabiani this PR finalizes all said and divides compose and swarm yaml files:
https://github.com/GeoNode/geonode-project/pull/274

one ca easy test it just running vagrant for compose ( on a virtualbox backend), which builds geonode and does a reboot of the vagrant virtualbox vm showing that containers start up correctly at boot, this should avoid further regression on containers repartition.

**Comment by afabiani** [comment]
@lpasquali can you please:

- this must be applied to "master" branch too
- the documentation must be updated too

**Comment by lpasquali** [comment]
@afabiani https://github.com/GeoNode/documentation/pull/216

**Comment by randomorder** [comment]
can we close @afabiani ?

**Comment by afabiani** [comment]
@randomorder yes, closing
