### ISSUE TITLE
Update env.sample variables

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-project#308]
- Add the following to the env sample
    - CELERY_BEAT_SCHEDULER=celery.beat:PersistentScheduler`
    - DEFAULT_MAX_UPLOAD_SIZE=5368709120
    - DEFAULT_MAX_PARALLEL_UPLOADS_PER_USER=5
- Remove 
    - `CACHE_BUSTING_MEDIA_ENABLED`

**Comment by giohappy** [comment]
@marthamareal do we need `CELERY_BEAT_SCHEDULER`. Its default is already that, and this isn't something we usually need to change in a project.
In any case, if we need to change it, we can always add it to the specific project.

I'm fine with the other two, since they can be something useful to configure per project.
