### ISSUE TITLE
docker base image 22.10 -> 22.04

### ISSUE THREAD

**Issue by openbrian** [GeoNode/geonode-project#487]
Please update Dockerfile according to this issue.

https://github.com/GeoNode/geonode/issues/11487

I'm using this and it's working so far.

```
FROM geonode/geonode-base:4.1.0-ubuntu-22.04
```

**Comment by giohappy** [comment]
@openbrian `geonode/geonode-base:4.1.0-ubuntu-22.04` is an old image, it's not updated to the latest 4.1.x changes. 
Branch 4.1.x is still using [local builds for GeoNode](https://github.com/GeoNode/geonode/blob/16797f4b9b6ae3d7f65f069ba06f2a89f5a8748b/Dockerfile#L1). The adoption of a published Docker image is only targeting the master branch.

Reverting master to Ubuntu 22.04 is not urgent at the moment, since `geonode/geonode-base:latest-ubuntu-22.10` is there, and there's no need to rebuild it at the moment. CircleCI and GeoNode Projects can use the published image, so at the moment we don't have the problems that lead to downgrading 4.1.x.
